{
  config,
  lib,
  pkgs,
  ...
}: let
  name = "sabnzbd";
  cfg = config.nps.stacks.${name};

  category = "Media & Downloads";
  displayName = "SABnzbd";
  description = "Usenet Client";

  storage = "${config.nps.storageBaseDir}/${name}";
  mediaStorage = "${config.nps.mediaStorageBaseDir}";
in {
  imports = import ../mkAliases.nix config lib name [name];

  options.nps.stacks.${name} = {
    enable = lib.mkEnableOption "SABnzbd";
    configIni = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      description = ''
        SABnzbd configuration mounted as `/config/sabnzbd.ini` in the container.
        The final configuration file will be templated with `gomplate`, so secrets can be read from files or environment variables.

        See <https://sabnzbd.org/wiki/configuration/5.0/configure>

        If left `null`, the configuration will be generated by SABnzbd on first start and can be configured via the web interface.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    services.podman.containers.${name} = {
      image = "lscr.io/linuxserver/sabnzbd:5.1.3";

      volumeMap = {
        config = "${storage}/config:/config";
        media = "${mediaStorage}:/media";
      };

      templateMount =
        lib.optional (cfg.configIni != null)
        {
          templatePath = pkgs.writeText "sabnzbd.ini" ''
            __version__ = 19
            __encoding__ = utf-8
            ${cfg.configIni}
          '';
          destPath = "/config/sabnzbd.ini";
        };

      environment = {
        PUID = config.nps.defaultUid;
        PGID = config.nps.defaultGid;
        UMASK = "022";
      };

      stack = name;
      port = 8080;
      traefik.name = name;
      homepage = {
        inherit category;
        name = displayName;
        settings = {
          description = description;
          icon = "sabnzbd";
          widget.type = "sabnzbd";
        };
      };
      glance = {
        inherit category;
        description = description;
        name = displayName;
        id = name;
        icon = "di:sabnzbd";
      };
    };
  };
}
