[book]
title = "Nix Podman Stacks"
language = "en"

[preprocessor.alerts]
renderers = ["html", "linkcheck"]

[output.html]
site-url = "/book/"
git-repository-url = "https://github.com/Tarow/nix-podman-stacks"

no-section-label = true
# Ensure static file (css, js) have a unique filename, to avoid outdated cache.
hash-files = true

[output.html.fold]
enable = false

[output.linkcheck]
follow-web-links = false
traverse-parent-directories = false
warning-policy = "error"
