{
 "title": "Traefik Access Log",
 "description": "Loki version 2 showcase using JSON Traefik access logs.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"traefik\"} |= `RequestProtocol` [$__interval]))"
    }
   ]
  },
  {
   "title": "% of  4/5xx ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": " sum(rate({container=\"traefik\"} |~ \"RequestProtocol\" | json | DownstreamStatus >= 400 |__error__=\"\"[$__interval])) / (sum(rate({container=\"traefik\"} |~ \"RequestProtocol\" | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Requests Route",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (RouterName) (count_over_time({container=\"traefik\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{RouterName}}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (DownstreamStatus) (count_over_time({container=\"traefik\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{DownstreamStatus}}"
    }
   ]
  },
  {
   "title": " 4/5xx  Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": " sum by (DownstreamStatus,ServiceName) (count_over_time({container=\"traefik\"} |~ \"RequestProtocol\" | json | DownstreamStatus >= 400 |__error__=\"\"[$__interval]))",
     "legendFormat": " {{ServiceName}} / {{DownstreamStatus}} "
    }
   ]
  },
  {
   "title": "Successful External Traffic",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"traefik\"} |= \"RequestProtocol\"\n| json\n| ClientAddr != ip(\"10.0.0.0/8\")\n| ClientAddr != ip(\"192.168.0.0/16\")\n| ClientAddr != ip(\"172.16.0.0/12\")\n| DownstreamStatus >= 200 and DownstreamStatus < 400\n| line_format \"Status:{{.DownstreamStatus}} - {{.ClientAddr}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}}\"\n"
    }
   ]
  },
  {
   "title": "Failed External Traffic",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"traefik\"} |= \"RequestProtocol\"\n| json\n| ClientAddr != ip(\"10.0.0.0/8\")\n| ClientAddr != ip(\"192.168.0.0/16\")\n| ClientAddr != ip(\"172.16.0.0/12\")\n| DownstreamStatus >= 400\n| line_format \"Status:{{.DownstreamStatus}} - {{.ClientAddr}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}}\""
    }
   ]
  },
  {
   "title": "External Traffic",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"traefik\"} |= \"RequestProtocol\"\n| json\n| ClientAddr != ip(\"10.0.0.0/8\")\n| ClientAddr != ip(\"192.168.0.0/16\")\n| ClientAddr != ip(\"172.16.0.0/12\")\n| line_format \"Status:{{.DownstreamStatus}} - {{.ClientAddr}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}}\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"traefik\"} |= \"RequestProtocol\"| json  | line_format \"Status:{{.DownstreamStatus}} - {{.ClientAddr}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}}\""
    }
   ]
  }
 ]
}